# Generated by Django 3.0.6 on 2020-05-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyddavaths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
